language: cpp
matrix:
        include:
                -name: "linux"
                os: linux
                compiler: gcc

                install:
                        - sudo apt-get install ftjam
                        - sudo apt-get install libgl1-mesa-dev
                        - wget -c https://github.com/15-466/nest-libs/releases/download/v0.0/nest-libs-linux-v0.0.tar.gz
                        - tar -zxvf nest-libs-linux-v0.0.tar.gz
                        - mv nest-libs ..
                -name: "mac"
                os: osx
                compiler: clang
                install:
                        - brew install ftjam
                        - wget -c https://github.com/15-466/nest-libs/releases/download/v0.0/nest-libs-macos-v0.0.tar.gz 
                        - tar -zxvf nest-libs-linux-v0.0.tar.gz
                        - mv nest-libs ..

script:
        jam
