language: cpp
compiler:
        - gcc
os: 
        - linux
before_install:
        - sudo apt-get install ftjam
install:
        - wget -c https://github.com/15-466/nest-libs/releases/download/v0.0/nest-libs-linux-v0.0.tar.gz
        - mkdir nest-libs
        - tar -C nest-libs -zxvf nest-libs-linux-v0.0.tar.gz
script:
        jam
