language: cpp
matrix:
        include:
              - name: "linux"
                os: linux
                compiler: gcc
                addons:
                        apt:
                                packages:
                                        - ftjam
                                        - libgl1-mesa-dev
                before_install:
                        - wget -c https://github.com/15-466/nest-libs/releases/download/v0.0/nest-libs-linux-v0.0.tar.gz
                        - tar -zxvf nest-libs-linux-v0.0.tar.gz
                        - mv nest-libs ..
                script: jam
              - name: "mac"
                os: osx
                compiler: clang
                before_install:
                        - brew install ftjam
                        - wget -c https://github.com/15-466/nest-libs/releases/download/v0.0/nest-libs-macos-v0.0.tar.gz 
                        - tar -xzvf nest-libs-macos-v0.0.tar.gz 
                        - mv nest-libs ..
                script: jam
              - name: "windows"
                os: windows
                before_install:
                        - choco install visualstudio2019buildtools ; true 
                        - choco install 7zip
                        - wget -c https://github.com/15-466/nest-libs/releases/download/v0.0/nest-libs-windows-v0.0.zip
                        - unzip -a nest-libs-windows-v0.0.zip
                        - mv nest-libs ..
                        - mv dirty_hack.bat ../nest-libs/windows/jam
                        - cd ../nest-libs/windows/jam
                script: cmd "/C call dirty_hack.bat"

