language: cpp
matrix:
  include:
  - name: linux
    os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - ftjam
        - libgl1-mesa-dev
    before_install:
    - wget -c https://github.com/15-466/nest-libs/releases/download/v0.0/nest-libs-linux-v0.0.tar.gz
    - tar -zxvf nest-libs-linux-v0.0.tar.gz
    - mv nest-libs ..
    script: jam
  - name: mac
    os: osx
    compiler: clang
    before_install:
    - brew install ftjam
    - wget -c https://github.com/15-466/nest-libs/releases/download/v0.0/nest-libs-macos-v0.0.tar.gz
    - tar -xzvf nest-libs-macos-v0.0.tar.gz
    - mv nest-libs ..
script:
- jam
- tar -czvf build.tar.gz dist/*
deploy:
  release: linux_and_mac
  params: env
  provider: releases
  file: build.tar.gz
  api_key: %api_key% 
  skip_cleanup: true
  on:
    tags: false
env:
  global:
    secure: RDFo4gHlAkLPf+vFE9K5rrCuE67bG1v5qN9i5fVxwgswzDAM7zPCGNfkRMmVuFhERJhkpwlrbOoXJ6OKFyA3r6zITQRLBdA63ShsUMUjNghSQEz9cc1n7Av2sfkwul1feD+JSYAaxhw8/g3UwfGIFFegVw0TxkZaF52qdnXou+DKH0N4DRyPcNGPKgulyLSzu5Zjj7mjT5oPacCmveHWk9hBT+pz6zxLtZmsK2xy49P7yFKOC3xmG7efWrwZqtzB06naTQERmAMlooClBKySUENGXurx1rVtHc5BVsgy1xTbxWpo5grgxMhaJ/8xG1udl95w4wL92Utu3uuA2+VhPjQ/UeU4BD48NX9Cpb+jZKXp7DvsSuR49LcIyVRTYcjQdn7uQK2OGZwm+iU0PM+LCh3gKiupjPBPtaxkuYLTQ4eeJ9eNDUL7wjQJDxZaJuWyY/Lvd1cPpHRhRgTvUtKhDXmVomgk8yGqfrEy/lA8HhiaAIGxg7jhenqe8Wty67RrSHNJYW4TQfB1TPyorMIzdAXONKVRpo1Oj7UcedSikpJt9g/AWA5k/WdTVO9S7lx6IWzlhqMF6nGs3RmNKYnoIQQ2KhCb9cfpF6zPI7wbNwqMwwZzCfls/FzsuOqlQdNgHqokmWE8pluFb/oVIsxO/KWsqXFnYvxguX4aAZ/qhU0=
